---
title: "Group Project"
author: "Wan Ting Hsu"
date: "2/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```

# Load packages
```{r}
library(dplyr)
library(tidyverse)
library(lubridate)
library(readr)
library(hrbrthemes)
library(bsts)
library(ggplot2)
library(patchwork)
```

#Read data (zikang edits)
```{r}

nypd <- read.csv(file.choose(), header = T)
nypd <- nypd %>% mutate(CMPLNT_FR_DT = mdy(CMPLNT_FR_DT ))
nypd$CMPLNT_FR_DT<-as.Date(nypd$CMPLNT_FR_DT)  


apply(nypd,
      MARGIN = 2, 
      FUN = function(x) sum(is.na(x)))

new <- nypd %>% 
  filter(CMPLNT_FR_DT >= "2018-03-01") %>%
  dplyr::select(CMPLNT_FR_DT, VIC_RACE,VIC_SEX, PD_DESC, SUSP_RACE, SUSP_SEX,) %>%
  group_by(CMPLNT_FR_DT, VIC_RACE) %>%
  count(VIC_RACE)

str(new)
colnames(new)[1] = "date"
colnames(new)[2] = "race"

bc <- new %>%
  filter(date <="2020-03-01")
ac <- new %>%
  filter(date > "2020-03-01")




```

#Clean data
```{r}
str(covid)
apply(covid,
      MARGIN = 2, 
      FUN = function(x) sum(is.na(x)))
```
Data parsing - covid

```{r}
covid <- covid %>% select(c(1:11)) %>% mutate(DATE_OF_INTEREST = mdy(DATE_OF_INTEREST ))
covid <- covid %>% filter(DATE_OF_INTEREST <= "2021-12-31")

summary(covid)

#covid[['month_year']] <- strptime(covid[['DATE_OF_INTEREST']],
                                            # format = "%Y-%m-%d")
covid$Month_Yr <- format(as.Date(covid$DATE_OF_INTEREST), "%Y-%m")
covid_monthly = aggregate(x = (case_count = covid$CASE_COUNT), by=list(Month_Yr=covid$Month_Yr), FUN=sum)
covid_monthly[nrow(covid_monthly) + 1,] <- c("2020-01", 0)
covid_monthly

covid$Month_Yr <- format(as.Date(covid$DATE_OF_INTEREST), "%Y-%m")
```

```{r}
apply(covid,
      MARGIN = 2, 
      FUN = function(x) sum(is.na(x)))

```

```{r}
str(crimes)
summary(crimes) 

```


Data parsing - crimes

```{r}
nypd <- nypd %>% mutate(CMPLNT_FR_DT = mdy(CMPLNT_FR_DT ))
nypd$CMPLNT_FR_DT<-as.Date(nypd$CMPLNT_FR_DT)  

```


```{r}

apply(nypd,
      MARGIN = 2, 
      FUN = function(x) sum(is.na(x)))

```
```{r}
new <- nypd %>% filter(CMPLNT_FR_DT >= 01/01/2017) %>% group_by(CMPLNT_FR_DT, VIC_RACE) 
new <- new %>% count(CMPLNT_NUM)
```



```{r}
write.csv(covid_monthly,"covid_monthly.csv",row.names = F)
write.csv(crimes,"crimes.csv",row.names = F)

```

#time series

```{r}
library(ggplot2);library(ggthemes);library(gridExtra)  # For plots 
library(quantmod);library(xts);library(zoo) # For using xts class objects
library(forecast) # Set of forecasting functions
library(fpp); library(fpp2) # Datasets from Forecasting text by Rob Hyndman
library(tseries) # for a statistical test
library(dplyr) # Data wrangling
```

#create ts object
```{r}


library("xts")

  
covid$DATE_OF_INTEREST<-as.Date(covid$DATE_OF_INTEREST)  
covid_ts <- xts(covid$CASE_COUNT, covid$DATE_OF_INTEREST)

  
is.xts(covid_ts)
```

```{r}
plot(covid_ts)
```



```{r}
crimes$Record.Create.Date<-as.Date(crimes$Record.Create.Date)  
asian <- crimes %>% filter(Bias.Motive.Description == "ANTI-ASIAN")
```


```{r}

asian_ts <- xts(asian)
is.xts(asian_ts)
```



```{r}
 nypd <- read.csv("NYPD_Complaint_Data_Current__Year_To_Date_.csv")
```

```{r}

```












